#!/bin/bash
# mondorestore.sh wrapper


verbose=""
output_directory="/mnt/sda4"
mount_directory="/mnt/share"

usage()
{
cat << EOF
usage: $0 -s 192.168.1.1:/share/ -f /path/to/isofile.iso

Automate system restoration from Mondo ISOs (both full and differential)

OPTIONS:
   -h      Show this message
   -s      NFS server address and share
   -f      Path to Full backup ISO
   -v      Verbose

Examples:
    $0 -s 192.168.1.1:/share/ -f /isos/gentoo-1.iso
EOF
}

exec_cmd()
{
    if [[ ! -z $verbose ]]
    then
        echo "Running: $1"
    fi
    # TODO: is that the right way to do it?
    $1
    if [ $? != 0 ]
    then
        echo "!! Error while running: $1 !!"
        echo "Try rerunning the script in verbose (-v) mode."
        echo ""
        exit 1
    fi
}

while getopts "hs:f:v" OPTION
do
     case $OPTION in
         h)
             usage
             exit
             ;;
         f)
             # path to full backup ISO
             iso_full_input_path=$OPTARG
             ;;
         s)
             # path to full backup ISO
             nfs_server=$OPTARG
             ;;
         v)
             verbose="-v"
             ;;
         ?)
             usage
             exit
             ;;
     esac
done

if [[ ! -z $iso_full_input_path ]] | [[ -z $nfs_server ]]
then
    usage
    exit 1
fi

exec_cmd "mount -t nfs $nfs_server $mount_directory"
exec_cmd "mondorestore.sh -f $mount_directory/$iso_full_input_path -o $output_directory $verbose"

